services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Cpsit\CpsUtility\:
    resource: '../Classes/*'

  Cpsit\CpsUtility\DataProcessor\FlexFormDataProcessor:
    tags:
      - { name: 'data.processor', identifier: 'FlexForm' }
